name: command
on: [push]
jobs:
  command:
    name: Use Linux commands
    runs-on: ubuntu-20.04
    steps:
    - name: create-json
      id: create-json-1
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "serviceAccountKey.json"
        json: ${{ secrets.SERVICEACCOUNTKEY_JSON }}
    
    - name: create-json
      id: create-json-2
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "fireBaseSDK.json"
        json: ${{ secrets.FIREBASESDK_JSON }}



